### ISSUE TITLE
Chat feature : Take in consideration [Team] and [All] channels in written logs

### ISSUE THREAD

**Issue by Undefined3301** [zayKenyon/VALORANT-rank-yoinker#109]
Console isn't showing (yet ?) the chat channel message was sent in, could be an improvement of the chat logging feature :).

**Comment by OwOHamper** [comment]
Added in 99fafc0561b1c13f6e717845986431f923f6094d

**Comment by Undefined3301** [comment]
The last update was really nice ! But it still lacks of the [All] and [Team] indicators, would that be possibly added :O ?
