### ISSUE TITLE
Feature : Write console outputs to File

### ISSUE THREAD

**Issue by Undefined3301** [zayKenyon/VALORANT-rank-yoinker#110]
A logging flag that could enable a write-to-file module to keep a trace of games we played and chat logs. (as it shows on the console I guess)
The actual log files are more technical than details printed on our console ...

**Comment by OwOHamper** [comment]
What would be use case of this?

**Comment by OwOHamper** [comment]
I mean could be added as an optional feature

**Comment by Undefined3301** [comment]
> I mean could be added as an optional feature

Yeah ! Like the chat print basically, by default to false, that's why I was mentioning the fact that it could be a flag 😃

**Comment by OwOHamper** [comment]
Added in 6d0ac04a20baa6dd79c84e2902240b033ba78b62 for now just terminal output but later will add more technical details
