### ISSUE TITLE
get_stats

### ISSUE THREAD

**Issue by rubi72** [zayKenyon/VALORANT-rank-yoinker#114]
![image](https://user-images.githubusercontent.com/81889577/186657689-1b719a43-4e9e-4aa8-97cf-f320411311c9.png)

**Comment by zayKenyon** [comment]
Please relaunch with [2.3.1](https://github.com/zayKenyon/VALORANT-rank-yoinker/releases/tag/2.31) and see if this re-occurs.

**Comment by rubi72** [comment]
> Please relaunch with [2.3.1](https://github.com/zayKenyon/VALORANT-rank-yoinker/releases/tag/2.31) and see if this re-occurs.

k let mc

**Comment by rubi72** [comment]
Lo mismo @zayKenyon 
![image](https://user-images.githubusercontent.com/81889577/186659129-80cee7d2-0b4f-4228-a13b-eb0d3c6ebdde.png)

**Comment by OwOHamper** [comment]
fixed in 2.32

**Comment by OwOHamper** [comment]
press enter
