### ISSUE TITLE
Chat Feature Enhancement : Show the channel a message is sent on

### ISSUE THREAD

**Issue by Undefined3301** [zayKenyon/VALORANT-rank-yoinker#116]
Added in 99fafc0561b1c13f6e717845986431f923f6094d

_Originally posted by @OwOHamper in https://github.com/zayKenyon/VALORANT-rank-yoinker/issues/109#issuecomment-1226358016_

The last update was really nice ! But it still lacks of the [All] and [Team] indicators, would that be possibly added :O ?

**Comment by OwOHamper** [comment]
Would be possible, will add

**Comment by OwOHamper** [comment]
Added in dc23784b5ca5f5e97cd64bb6ba4f7aea4ebc625b
