### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by zayKenyon** [zayKenyon/VALORANT-rank-yoinker#123]
Judging by our 3 different file naming conventions and countless more variable naming conventions, I think it's time to standardise.

After doing some research, I think we should go with [pycodestyle](https://pypi.org/project/pycodestyle); it uses the [PEP 8](https://peps.python.org/pep-0008/) convention, which we started using with #115.

**Comment by zayKenyon** [comment]
After some consideration, we will go with [pylint](https://pypi.org/project/pylint/) due to it's ability to [integrate](https://pylint.pycqa.org/en/latest/user_guide/installation/ide_integration/index.html#ide-integration) with IDEs and code editors.

**Comment by ThisIsTeddyBear** [comment]
I did not understand the complete issue but I think, I can help can someone link or please refer to what all are the pending items in this issue.
And finally what is the coding standard  decided and finally being used.

**Comment by zayKenyon** [comment]
> I did not understand the complete issue but I think, I can help can someone link or please refer to what all are the pending items in this issue. And finally what is the coding standard decided and finally being used.

There is an old list of files in #124 . This PR is mainly about addressing the numerous different code styles we have running throughout the project, and also removing redudant code (mainly code that's commented out). As for code style, I plan to follow *most* of PEP8, but I don't have a list of what I'm deeming unreasonable. 

You can make a new PR superseeding #124 , but if you're looking for more immediate merges than I'd recommend working on issues with the 'bug' flair too.
