### ISSUE TITLE
Force Widen Terminal Window

### ISSUE THREAD

**Issue by Undefined3301** [zayKenyon/VALORANT-rank-yoinker#127]
The printed board if the console doesn't fit the columns amount is buggy, and it keeps being badly printed after resizing the window, unlike having the right size from the beginning (that requires the user to resize the console window asap after opening vry).

Maybe there's something that scales the board to the window size but it seems like it just breaks the board, even more after rescaling the window to a higher surface.

I could provide screenshots if it's not enough clear, but it can be easily reproduced, just enable all columns available (and even one more in immortal if the guy is on the leaderboard) without resizing the console after launch, and see the result on match 😅

**Comment by OwOHamper** [comment]
Making terminal wider is bad solution instead I found a way to expand it to max size without resizing terminal, will come in next update.

**Comment by zayKenyon** [comment]
Fixed in 188a3f0.
