### ISSUE TITLE
Chat messages duplicating

### ISSUE THREAD

**Issue by Noriaela** [zayKenyon/VALORANT-rank-yoinker#128]
I do not know how to recreate this issue, but it's something I've noticed that's happening recently. Totally possible it's just a me issue.
![WindowsTerminal_WcR2hPxFf6](https://user-images.githubusercontent.com/22671423/188197657-39a87589-a166-4abc-a546-f116a2ed924b.png)

**Comment by OwOHamper** [comment]
Messages have id and if the id has already been printed than it won't be printed again. Also messages are only limited to 5, is it possible you are running an old version?

**Comment by Noriaela** [comment]
> Messages have id and if the id has already been printed than it won't be printed again. Also messages are only limited to 5, is it possible you are running an old version?

I just cloned the repo and have been git pulling every time there's an update so it's possible that why. I'll use the latest release version and check later.

**Comment by Noriaela** [comment]
Using the latest release and I'm not running into the issue anymore. 

Closing issue now
