### ISSUE TITLE
Consider adding this to hacktoberfest ? 

### ISSUE THREAD

**Issue by AnkushMalaker** [zayKenyon/VALORANT-rank-yoinker#130]
I'm not sure if this is the right place to ask for this, consider adding this to hacktoberfest. Many would like to contribute to this and play around, and college kids in my area who play valorant would be motivated to contribute to open source for the first time :)
Thanks.

**Comment by zayKenyon** [comment]
Sorry for the late response.

What is Hacktoberfest? What would we have to do and what does this mean for vRY? Do we need to change something in our repo to make our project hacktoberfest friendly?
