### ISSUE TITLE
Previous player in party still on table

### ISSUE THREAD

**Issue by tokinaa** [zayKenyon/VALORANT-rank-yoinker#131]
![image](https://user-images.githubusercontent.com/67111486/204589805-a066028d-ccfa-4b82-9f2f-e4d2b48278aa.png)

I got this maybe glitch or minor bugs(?), previously p1 in my team, then he leave. another player join. so we playing.
But, after the result, p1 still in my team table. 

Anyone got this problem too ?

**Comment by OwOHamper** [comment]
This must be problem of valorant presences (friend list) not updating.
