### ISSUE TITLE
Bitdefender suddenly deleted yoinker off my desktop

### ISSUE THREAD

**Issue by tedulous** [zayKenyon/VALORANT-rank-yoinker#133]
I've been using it for months but I think some random update on their end may have made it think the app is a trojan. 

Says something about this line Gen:Suspicious.Cloud.4.iy0@aaqbJnmi

**Comment by OwOHamper** [comment]
https://github.com/zayKenyon/VALORANT-rank-yoinker/issues/13

**Comment by tedulous** [comment]
> #13

I am aware of that thread but there's no mention of a work around

**Comment by OwOHamper** [comment]
Running source or excluding the .exe in your antivirus

**Comment by tedulous** [comment]
> 

cant really do that if it deletes the file the moment i download it

**Comment by OwOHamper** [comment]
Go to your antivirius quaranteen and add it back from there and add it in exclusions.
