### ISSUE TITLE
VRY not opening

### ISSUE THREAD

**Issue by Veloctyy** [zayKenyon/VALORANT-rank-yoinker#134]
I tried opening VRY multiple times and nothing happens nothing pop ups. I have valorant open and i reinstalled and restarted pc and nothing fixed.

**Comment by nchmielewski** [comment]
silly question but are you using the command line interface

**Comment by Veloctyy** [comment]
When I type main.py is says 'main.py' is not recognized as an internal or external command, operable program or batch file. I also do have python and I did use to use very is just randomly stopped working.  https://cdn.discordapp.com/attachments/619223191230873620/1060910617063591936/Screenshot_336.png

**Comment by OwOHamper** [comment]
You have to type `python main.py` not just `main.py` if it doesn't work also try `python3 main.py`.

**Comment by Veloctyy** [comment]
It now says python was not found https://cdn.discordapp.com/attachments/619223191230873620/1060917600009326612/Screenshot_337.png

**Comment by OwOHamper** [comment]
Have you ttied python3?

**Comment by Veloctyy** [comment]
no how do you do that?

**Comment by OwOHamper** [comment]
type 'python3 main.py'

**Comment by Veloctyy** [comment]
oh yes i tried both

**Comment by OwOHamper** [comment]
Then you will need to install python

**Comment by Veloctyy** [comment]
i have python installed i just installed the most recent version and restarted my PC

**Comment by OwOHamper** [comment]
you needed to check the option "add to path" during installation run the installation again and modify the installation and add to it to path

**Comment by Veloctyy** [comment]
I reinstalled and now i get this message https://cdn.discordapp.com/attachments/619223191230873620/1060932140134572032/Screenshot_338.png

**Comment by OwOHamper** [comment]
ah you are not running source code, then you don't even need python just open the command prompt and type `vry.exe` or whatever the name is

**Comment by Veloctyy** [comment]
thank this worked
