### ISSUE TITLE
Bug: Not detecting Python install

### ISSUE THREAD

**Issue by akulakovsky** [zayKenyon/VALORANT-rank-yoinker#135]
If you run vry.exe before you have Python in your path, it'll continue assuming it's not in your path until you reinstall with the same error as this issue https://github.com/zayKenyon/VALORANT-rank-yoinker/issues/96

**Comment by akulakovsky** [comment]
I'd also suggest noting having Python installed and in your PATH in the README.

**Comment by OwOHamper** [comment]
Download [Python 3.10](https://www.python.org/downloads/release/python-3100/), **make sure it is added to the PATH. (This is an option on installation.)**

    Any Python version post 3.8 should work.

**Comment by akulakovsky** [comment]
I know, I got it to work before making this issue. I'm reporting what I believe is a bug.

Let me try to better explain. 
1. I initially didn't have Python installed (since it didn't mention it anywhere in ["Bundled Release"](https://github.com/zayKenyon/VALORANT-rank-yoinker#bundled-release) section).
2. I ran `vry.exe` and got this error: `Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'`
3. I installed Python and added it to my path.
4. I re-ran `vry.exe`.
5. Still had the same error. <--- The bug
6. Deleted the install folder, redownloaded the zip, extracted it, ran `vry.exe` and now it works.

**Comment by OwOHamper** [comment]
Anyways for running `vry.exe` you shouldn't have to install Python. Sounds like the release .zip could be corrupted? Not sure

**Comment by akulakovsky** [comment]
Oh, that's weird. I think the bug I described might still apply for if you "run from source", though.

**Comment by zayKenyon** [comment]
> Still had the same error. <--- The bug
> Deleted the install folder, redownloaded the zip, extracted it, ran vry.exe and now it works.

Judging that you absolutely do not need Python for the bundled release, I agree that this sounds like a corrupted .zip. 
As a result I'm closing this issue, feel free to make anew if this happens again.
