### ISSUE TITLE
The program has encountered an error!

### ISSUE THREAD

**Issue by imshantanu** [zayKenyon/VALORANT-rank-yoinker#140]
while launching the VRY I am getting this error
log file attached kindly help me.
[log-1.txt](https://github.com/zayKenyon/VALORANT-rank-yoinker/files/10875538/log-1.txt)
![Screenshot (3)](https://user-images.githubusercontent.com/20909543/222544988-18cf7cd1-1d7c-411e-964c-09029712ed75.png)

**Comment by zayKenyon** [comment]
Hi! 

I'd like to immediately suggest that you join the [Discord](https://discord.gg/HeTKed64Ka) for more real-time support.

Analysing your uploaded logfile, I see the WinError10054. I suggest following these steps:

* Start off by checking your firewall settings to see if it is being blocked, temporarily disabling your firewall will confirm this. 
* If needed, you could then try to restart: vRY, but if that doesn't fix it then VALORANT, but then if that doesn't fix it then your computer. 
* If you have a slower internet connection then changing the value of cooldown located in config.json to 0 (manual refresh) or to something > 1 may help.
* If that doesn't work then changing the port located within the config.json file may work.
