### ISSUE TITLE
Possible to contribute to the web app?

### ISSUE THREAD

**Issue by veritymedia** [zayKenyon/VALORANT-rank-yoinker#151]
I would like to contribute to the web app, is it open source? I was actually thinking of wrapping the app in a tauri based exec and having the info from the CLI app and the web app integrated in one fast launching app.

Let me know what I can do.

**Comment by OwOHamper** [comment]
Hello, the web app is under the branch [`vue.js`](https://github.com/zayKenyon/VALORANT-rank-yoinker/tree/vue.js).
