### ISSUE TITLE
why does streamer mode hide names in vry but valorant tracker can bypass it

### ISSUE THREAD

**Issue by horizon1g** [zayKenyon/VALORANT-rank-yoinker#158]
so if you have valorant tracker you can see names of people who have streamer mode enabled but vry has disabled this, so why is it not a thing anymore

**Comment by OwOHamper** [comment]
Because riot got angry, they didn't like it, so we updated it and they gave 7-day suspensions to people who didn't update.

**Comment by ThisIsTeddyBear** [comment]
@horizon1g Which Valorant tracker shows hidden names ?
