### ISSUE TITLE
Error in viewing skins in browser.

### ISSUE THREAD

**Issue by ThisIsTeddyBear** [zayKenyon/VALORANT-rank-yoinker#159]
When the link (_https://vry.netlify.app/matchLoadouts_) is opened and when it redirects to the browser it never shows any skins and just always shows the same message as "no match cache found".

How can this problem be fixed and am i the only one who is facing this issue.
**Been using YOINKER for almost a year and was never able to see the skins in browser.**
@OwOHamper @zayKenyon Any fixes ?

**Comment by nanometer5088** [comment]
This is likely an issue on your end, the website works fine, and has been since it's introduction.

If you're running Brave Browser and / or have any content blocker extension, I suggest you to disable it on the website, since they frequently block the interaction of websites with LAN

**Comment by ThisIsTeddyBear** [comment]
Yup thanks it works in Edge, is there anyway in which I can make it work in Brave browser ?

**Comment by nanometer5088** [comment]
> is there anyway in which I can make it work in Brave browser ?

Yes, it's quite simple! Just disable Brave Shields and any content blocking extension that you might have installed, and it should work fine on Brave Browser

**Comment by ThisIsTeddyBear** [comment]
Thanks a lot I'm just dumb my bad.
