### ISSUE TITLE
Does not display party status

### ISSUE THREAD

**Issue by LynxtX** [zayKenyon/VALORANT-rank-yoinker#181]
![image](https://github.com/zayKenyon/VALORANT-rank-yoinker/assets/89693370/b6058c6e-c25a-4bf9-ad01-9794ea53a17a)
![image](https://github.com/zayKenyon/VALORANT-rank-yoinker/assets/89693370/b01111b7-556b-481f-a2ab-6a53fd2cf041)

For some reason, vry stopped displaying if players are in a party

**Comment by YomYom23** [comment]
having the same problem

**Comment by zayKenyon** [comment]
Succeeded by #186
