### ISSUE TITLE
no vRY.exe file in export

### ISSUE THREAD

**Issue by blossoo** [zayKenyon/VALORANT-rank-yoinker#184]
![image](https://github.com/zayKenyon/VALORANT-rank-yoinker/assets/106000067/6539bfa1-9c49-4ac3-80c7-b0f276eba59a)
Following the first section of instructions, however when I search in my files as well as the GitHub itself I can not locate the vRY.exe file name. Where can I find it? Thank you.

**Comment by zayKenyon** [comment]
Hey there, your extracted folder doesn't seem to have all the files it should! Please try download again from the releases tab, or use this [direct link](https://github.com/zayKenyon/VALORANT-rank-yoinker/releases/download/2.60/VALORANT-rank-yoinker_2.60.zip). I'm not sure where index comes from as I can't see that in any of our branches 🤔.
