### ISSUE TITLE
Ban alert!!

### ISSUE THREAD

**Issue by d0tzerr** [zayKenyon/VALORANT-rank-yoinker#196]
Just got banned for using it. Permantent suspention, be careful!!

**Comment by zayKenyon** [comment]
Riot historically have not handed out permanent suspensions for 3rd party apps, at least, not for the first or second punishments 👀.

I'll keep an eye out for other reports, but for now, it was likely some other software that you continued to use over your first and second sanctions.

**Comment by tokinaa** [comment]
No proof banned, i was tried this from repository created untill now lol.

**Comment by xlegends** [comment]
confirmed to be unbanable?
