### ISSUE TITLE
RR lost or gained in last three competitive games	

### ISSUE THREAD

**Issue by Ashesh3** [zayKenyon/VALORANT-rank-yoinker#81]
Is it possible to add a column which shows the RR lost or gained in last three competitive games?

![image](https://user-images.githubusercontent.com/3626859/176672060-ff3aea63-3826-40bc-90a7-144e352152b5.png)

**Comment by Soneliem** [comment]
Hmmmm

**Comment by OwOHamper** [comment]
Yep, that would be possible could be added as optional collumn.
