### ISSUE TITLE
Error running VRY

### ISSUE THREAD

**Issue by UnPurgable** [zayKenyon/VALORANT-rank-yoinker#96]
Microsoft Windows [Version 10.0.22000.795]
(c) Microsoft Corporation. All rights reserved.

C:\Users\dle45>C:\Users\dle45\OneDrive\Desktop\vry.exe
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\Users\dle45\OneDrive\Desktop\vry.exe'
  isolated = 0
  environment = 0
  user site = 1
  import site = 0
  sys._base_executable = 'C:\\Users\\dle45\\OneDrive\\Desktop\\vry.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\dle45\\OneDrive\\Desktop\\vry.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\dle45\\OneDrive\\Desktop\\lib\\library.zip',
    'C:\\Users\\dle45\\OneDrive\\Desktop\\lib',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000d10 (most recent call first):
  <no Python frame>

C:\Users\dle45>

**Comment by zayKenyon** [comment]
Add Python to PATH
